export const tasks1 = [
  {
    id: 1,
    instruction: "Calculate the following expressions",
    correctAnswers: 0,
    problems: [
      {
        id: 1,
        exercise: "27+39+13+11",
        answer: 90,
        result: null,
        userInput: "",
      },
      {
        id: 2,
        exercise: "18+39+27+12+2",
        answer: 119,
        result: null,
        userInput: "",
      },
      {
        id: 3,
        exercise: "38+94+12+16",
        answer: 160,
        result: null,
        userInput: "",
      },
      {
        id: 4,
        exercise: "116+37+14+43",
        answer: 210,
        result: null,
        userInput: "",
      },
      {
        id: 5,
        exercise: "29+87+21+51+13",
        answer: 201,
        result: null,
        userInput: "",
      },
      {
        id: 6,
        exercise: "155+46+5+54+30",
        answer: 290,
        result: null,
        userInput: "",
      },
      {
        id: 7,
        exercise: "198+36+102+64+75",
        answer: 475,
        result: null,
        userInput: "",
      },
      {
        id: 8,
        exercise: "122+193+27+78+15",
        answer: 435,
        result: null,
        userInput: "",
      },
      {
        id: 9,
        exercise: "527+108+11+73+39+92",
        answer: 850,
        result: null,
        userInput: "",
      },
      {
        id: 10,
        exercise: "401+223+49+77+54",
        answer: 804,
        result: null,
        userInput: "",
      },
      {
        id: 11,
        exercise: "217+125+49+111+83+75",
        answer: 660,
        result: null,
        userInput: "",
      },
      {
        id: 12,
        exercise: "326+157+74+43+229",
        answer: 829,
        result: null,
        userInput: "",
      },
      {
        id: 13,
        exercise: "303+144+67+56+137",
        answer: 707,
        result: null,
        userInput: '',
      },
      {
        id: 14,
        exercise: "73+111+257+89+201",
        answer: 731,
        result: null,
        userInput: '',
      },
      {
        id: 15,
        exercise: "845+136+155+164+208",
        answer: 1508,
        result: null,
        userInput: '',
      },
    ],
  },
  {
    id: 2,
    instruction: "Find the result",
    correctAnswers: 0,
    problems: [
      {
        id: 1,
        exercise: "3080+6385-7967",
        answer: 1498,
        result: null,
        userInput: "",
      },
      {
        id: 2,
        exercise: "10000-4657-3886",
        answer: 1457,
        result: null,
        userInput: "",
      },
      {
        id: 3,
        exercise: "302506-128567-0+13585",
        answer: 187524,
        result: null,
        userInput: "",
      },
      {
        id: 4,
        exercise: "6547-6547",
        answer: 0,
        result: null,
        userInput: "",
      },
      {
        id: 5,
        exercise: "137-0-137+0",
        answer: 0,
        result: null,
        userInput: "",
      },
      {
        id: 6,
        exercise: "9084-7556+386+0",
        answer: 1914,
        result: null,
        userInput: "",
      },
      {
        id: 7,
        exercise: "64537-45289-19248-0",
        answer: 0,
        result: null,
        userInput: "",
      },
      {
        id: 8,
        exercise: "53032+0-49769+5007",
        answer: 8270,
        result: null,
        userInput: "",
      },
    ],
  },
];


const lessons = [
  {
    id: 1,
    title: "Arithmetics of Natual Numbers",
    caption: "Perform multi-step calculations with natural numbers",
    tasks: 23,
    exercises: 207,
    subsections: [
      "addition",
      "division",
      "subtraction",
      "multiplication",
      "naturals",
    ],
  },
  {
    id: 2,
    title: "Divisibility Rules",
    caption: "Rules to determine if a number is divisible by another number",
    tasks: 12,
    exercises: 126,
    subsections: ["factors", "divisibility"],
  },
  {
    id: 3,
    title: "Prime Decomposition of Natual Numbers",
    caption: "Expressing numbers as a multiplication of prime numbers",
    tasks: 18,
    exercises: 89,
    subsections: ["primes", "distinct prime factors", "exponent"],
  },
  {
    id: 4,
    title: "GCF & LCM",
    caption: "Greatest Common Factor & Least Common Multiples",
    tasks: 23,
    exercises: 186,
    subsections: [
      "factors",
      "divisibility",
      "primes",
      "distinct prime factors",
    ],
  },
];


export default lessons;
